# Generated by Django 4.2.1 on 2025-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='yulia.iakovleva@uni-konstanz.de', max_length=100),
        ),
    ]
