# Generated by Django 4.2.1 on 2025-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistype',
            name='ordered_footprint_list',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='species',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
