"""empty message

Revision ID: 7c0678cd145d
Revises: e57014d6313f
Create Date: 2020-07-11 15:18:17.756606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0678cd145d'
down_revision = 'e57014d6313f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_index('ix_data_set_data_name', table_name='data_set')
    op.drop_index('ix_data_set_study_name', table_name='data_set')
    op.drop_index('ix_data_set_study_to_load_str', table_name='data_set')
    op.drop_index('ix_data_set_upload_timestamp', table_name='data_set')
    op.drop_table('data_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('study_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('study_to_load_str', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('location', sa.VARCHAR(length=64), nullable=True),
    sa.Column('num_samples', sa.INTEGER(), nullable=True),
    sa.Column('additional_markers', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('run_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('article_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('seq_data_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('data_explorer', sa.BOOLEAN(), nullable=True),
    sa.Column('author_list_string', sa.VARCHAR(length=500), nullable=True),
    sa.Column('analysis', sa.BOOLEAN(), nullable=True),
    sa.Column('upload_timestamp', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('analysis IN (0, 1)'),
    sa.CheckConstraint('data_explorer IN (0, 1)'),
    sa.CheckConstraint('is_published IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_set_upload_timestamp', 'data_set', ['upload_timestamp'], unique=False)
    op.create_index('ix_data_set_study_to_load_str', 'data_set', ['study_to_load_str'], unique=1)
    op.create_index('ix_data_set_study_name', 'data_set', ['study_name'], unique=1)
    op.create_index('ix_data_set_data_name', 'data_set', ['data_name'], unique=1)
    op.create_table('datasets',
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'user_id')
    )
    # ### end Alembic commands ###
