"""initial migration

Revision ID: e57014d6313f
Revises: 
Create Date: 2019-12-18 09:37:00.474504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57014d6313f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_name', sa.String(length=64), nullable=True),
    sa.Column('study_name', sa.String(length=64), nullable=True),
    sa.Column('study_to_load_str', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('additional_markers', sa.String(length=200), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('run_type', sa.String(length=64), nullable=True),
    sa.Column('article_url', sa.String(length=200), nullable=True),
    sa.Column('seq_data_url', sa.String(length=200), nullable=True),
    sa.Column('data_explorer', sa.Boolean(), nullable=True),
    sa.Column('author_list_string', sa.String(length=500), nullable=True),
    sa.Column('analysis', sa.Boolean(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_set_data_name'), 'data_set', ['data_name'], unique=True)
    op.create_index(op.f('ix_data_set_study_name'), 'data_set', ['study_name'], unique=True)
    op.create_index(op.f('ix_data_set_study_to_load_str'), 'data_set', ['study_to_load_str'], unique=True)
    op.create_index(op.f('ix_data_set_upload_timestamp'), 'data_set', ['upload_timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_data_set_upload_timestamp'), table_name='data_set')
    op.drop_index(op.f('ix_data_set_study_to_load_str'), table_name='data_set')
    op.drop_index(op.f('ix_data_set_study_name'), table_name='data_set')
    op.drop_index(op.f('ix_data_set_data_name'), table_name='data_set')
    op.drop_table('data_set')
    # ### end Alembic commands ###
